// @generated Code generated by thrift-gen. Do not modify.

// Package tcollector is generated code used to make or handle TChannel calls using Thrift.
package tcollector

import (
	"fmt"

	athrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/tchannel-go/thrift"
)

// Interfaces for the service and client for the services defined in the IDL.

// TChanTCollector is the interface that defines the server handler and client interface.
type TChanTCollector interface {
	MultiSubmit(ctx thrift.Context, spans []*Span) ([]*Response, error)
	Submit(ctx thrift.Context, span *Span) (*Response, error)
}

// Implementation of a client and service handler.

type tchanTCollectorClient struct {
	thriftService string
	client        thrift.TChanClient
}

func newTChanTCollectorClient(thriftService string, client thrift.TChanClient) *tchanTCollectorClient {
	return &tchanTCollectorClient{
		thriftService,
		client,
	}
}

// NewTChanTCollectorClient creates a client that can be used to make remote calls.
func NewTChanTCollectorClient(client thrift.TChanClient) TChanTCollector {
	return newTChanTCollectorClient("TCollector", client)
}

func (c *tchanTCollectorClient) MultiSubmit(ctx thrift.Context, spans []*Span) ([]*Response, error) {
	var resp TCollectorMultiSubmitResult
	args := TCollectorMultiSubmitArgs{
		Spans: spans,
	}
	success, err := c.client.Call(ctx, c.thriftService, "multi_submit", &args, &resp)
	if err == nil && !success {
	}

	return resp.GetSuccess(), err
}

func (c *tchanTCollectorClient) Submit(ctx thrift.Context, span *Span) (*Response, error) {
	var resp TCollectorSubmitResult
	args := TCollectorSubmitArgs{
		Span: span,
	}
	success, err := c.client.Call(ctx, c.thriftService, "submit", &args, &resp)
	if err == nil && !success {
	}

	return resp.GetSuccess(), err
}

type tchanTCollectorServer struct {
	handler TChanTCollector
}

func newTChanTCollectorServer(handler TChanTCollector) *tchanTCollectorServer {
	return &tchanTCollectorServer{
		handler,
	}
}

// NewTChanTCollectorServer wraps a handler for TChanTCollector so it can be
// registered with a thrift.Server.
func NewTChanTCollectorServer(handler TChanTCollector) thrift.TChanServer {
	return newTChanTCollectorServer(handler)
}

func (s *tchanTCollectorServer) Service() string {
	return "TCollector"
}

func (s *tchanTCollectorServer) Methods() []string {
	return []string{
		"multi_submit",
		"submit",
	}
}

func (s *tchanTCollectorServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	var args interface{}
	var err error
	switch methodName {
	case "multi_submit":
		args, err = s.readMultiSubmit(protocol)
		if err != nil {
			return false, nil, err
		}
	case "submit":
		args, err = s.readSubmit(protocol)
		if err != nil {
			return false, nil, err
		}
	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
	return s.HandleArgs(ctx, methodName, args)
}

func (s *tchanTCollectorServer) HandleArgs(ctx thrift.Context, methodName string, args interface{}) (bool, athrift.TStruct, error) {
	switch methodName {
	case "multi_submit":
		return s.handleMultiSubmit(ctx, args.(TCollectorMultiSubmitArgs))
	case "submit":
		return s.handleSubmit(ctx, args.(TCollectorSubmitArgs))
	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}

func (s *tchanTCollectorServer) readMultiSubmit(protocol athrift.TProtocol) (interface{}, error) {
	var req TCollectorMultiSubmitArgs

	if err := req.Read(protocol); err != nil {
		return nil, err
	}
	return req, nil
}

func (s *tchanTCollectorServer) handleMultiSubmit(ctx thrift.Context, req TCollectorMultiSubmitArgs) (bool, athrift.TStruct, error) {
	var res TCollectorMultiSubmitResult
	r, err :=
		s.handler.MultiSubmit(ctx, req.Spans)

	if err != nil {
		return false, nil, err
	} else {
		res.Success = r
	}

	return err == nil, &res, nil
}

func (s *tchanTCollectorServer) readSubmit(protocol athrift.TProtocol) (interface{}, error) {
	var req TCollectorSubmitArgs

	if err := req.Read(protocol); err != nil {
		return nil, err
	}
	return req, nil
}

func (s *tchanTCollectorServer) handleSubmit(ctx thrift.Context, req TCollectorSubmitArgs) (bool, athrift.TStruct, error) {
	var res TCollectorSubmitResult
	r, err :=
		s.handler.Submit(ctx, req.Span)

	if err != nil {
		return false, nil, err
	} else {
		res.Success = r
	}

	return err == nil, &res, nil
}
